### ISSUE TITLE
Add name to the Connection Settings

### ISSUE THREAD

**Issue by stbischof** [amitjoy/osgifx#388]
**Is your feature request related to a problem? Please describe.**
could no remember which agent on which port is.

**Describe the solution you'd like**
Add a optional Name to Connection settings and add this name in the Connections-Table.

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by amitjoy** [comment]
It could be a very useful feature to associate names to the the connection configurations. Thanks a lot for your proposal 👍
