### ISSUE TITLE
Instructions to set up an IDE for contributing

### ISSUE THREAD

**Issue by doggy-dev** [amitjoy/osgifx#605]
**Is your feature request related to a problem? Please describe.**
As a contributor I can check out the code but I'm familiar with the intended development workflow.

**Describe the solution you'd like**
As a contributor I need instructions how to set up my development environment.

**Describe alternatives you've considered**

**Additional context**

**Comment by amitjoy** [comment]
You can find the instructions under `Project Import for Development` on the project website - http://osgifx.com

**Comment by doggy-dev** [comment]
Oh thanks.
